name: 'Pull Request Version Check'
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull Request Version Check
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
